/**
 * `word_update`: append paragraphs, bullets, and one table to an existing
 * .docx (1.0.0). The appended body children are generated by the same part
 * builder word_create uses, then spliced into the document's body right
 * before its trailing `<w:sectPr>`. The archive is re-emitted as an
 * ASCII-safe STORE package through the official fs channel, so updates are
 * limited to packages whose every part can round-trip as ASCII text — always
 * true for files these tools write, and for any OOXML package that carries
 * no binary media.
 */
import type { Context } from '@deepseek-ai/cordis';
import type { FsContext } from '../fschannel.ts';
export declare function registerWordUpdate(ctx: Context & FsContext): () => void;
