/**
 * Word (.docx) tools over the self-contained OOXML container (1.0.0):
 * `word_create` builds a styled document part set directly (no third-party
 * library — the package is an ASCII-safe STORE zip written through the
 * official fs channel); `word_read` extracts plain text or markdown with the
 * same in-house regex extractor whose behavior is pinned to mammoth 1.11.0's
 * raw-text output by `tests/word-parity.spec.ts`.
 */
import type { Context } from '@deepseek-ai/cordis';
import type { FsContext } from '../fschannel.ts';
export interface WordCreateArgs {
    path: string;
    title?: string;
    paragraphs?: string[];
    bullets?: string[];
    table?: {
        headers: string[];
        rows: string[][];
    };
    overwrite?: boolean;
}
export interface WordUpdateArgs {
    path: string;
    paragraphs?: string[];
    bullets?: string[];
    table?: {
        headers: string[];
        rows: string[][];
    };
}
export declare function wordCreateCounts(args: WordUpdateArgs & {
    title?: string;
}): {
    paragraphs: number;
    cells: number;
};
/** Build the complete .docx package as an ASCII-safe zip string. */
export declare function buildDocxText(args: WordUpdateArgs & {
    title?: string;
}): string;
/**
 * Extract mammoth-compatible plain text from a `word/document.xml` string:
 * every paragraph — body, table cell, hyperlink, or textbox — contributes its
 * runs followed by `\n\n`, including the final and empty paragraphs.
 */
export declare function extractDocxText(documentXml: string): string;
/**
 * Extract structured markdown from a `word/document.xml` string: Title and
 * Heading1-6 render as `#`..`######`, numbered/bullet paragraphs as indented
 * `- ` items, tables as markdown tables, everything else as plain blocks —
 * inline rules identical to {@link extractDocxText}.
 */
export declare function extractDocxMarkdown(documentXml: string): string;
/**
 * Body children for an append, generated by the same part builder
 * word_create uses (so paragraphs, bullets, and tables come out identical)
 * and extracted from the throwaway document minus its trailing `<w:sectPr>`.
 */
export declare function buildAppendFragment(args: WordUpdateArgs): string;
/**
 * Splice new body children into `word/document.xml`: appended content goes
 * right before the trailing `<w:sectPr>` (page setup must stay the last body
 * child), or before `</w:body>` when the document has no section properties.
 */
export declare function appendBeforeSectPr(documentXml: string, addition: string): string;
export declare function registerWordTools(ctx: Context & FsContext): () => void;
