/**
 * `word_update`: append paragraphs, bullets, and one table to an existing
 * .docx (1.0.0). The appended body children are generated by the same part
 * builder word_create uses, then spliced into the document's body right
 * before its trailing `<w:sectPr>`. The archive is re-emitted as an
 * ASCII-safe STORE package through the official fs channel, so updates are
 * limited to packages whose every part can round-trip as ASCII text — always
 * true for files these tools write, and for any OOXML package that carries
 * no binary media.
 */

import type { Context } from '@deepseek-ai/cordis'
import { defineTool } from '@deepseek-ai/dsh-tools'
import type { ToolRunContext } from '@deepseek-ai/dsh-tools'
import { buildAsciiZip, readZip, readZipXmlPart, type ZipPart } from '../asciizip.ts'
import type { FsContext } from '../fschannel.ts'
import { readOfficeBytes, resolveOfficePath, saveOfficeText } from '../fschannel.ts'
import { FILE_RESULT_SCHEMA } from './shared.ts'
import { appendBeforeSectPr, buildAppendFragment, wordCreateCounts, type WordUpdateArgs } from './word.ts'

const WORD_UPDATE_OUTPUT = {
  type: 'object',
  additionalProperties: false,
  properties: {
    ...FILE_RESULT_SCHEMA.properties,
    appendedParagraphs: { type: 'integer', required: true },
    appendedBullets: { type: 'integer', required: true },
    appendedTableRows: { type: 'integer', required: true },
  },
} as const

export function registerWordUpdate(ctx: Context & FsContext): () => void {
  return ctx.tools.register(defineTool({
    name: 'word_update',
    description:
      'Append content to an existing .docx Word document in the session workspace: paragraphs, bullet points, and/or one table are added at the end of the body (in that order), leaving everything already in the file untouched. '
      + 'Bullets reuse the list numbering the document already defines, so they render as bullets in files that have them (files created by word_create always do); documents without list numbering show appended bullets as plain paragraphs. '
      + 'The file is re-published atomically through the official workspace file service; packages with binary parts (embedded images or fonts) cannot be rewritten and are refused. Use word_read afterwards to verify.',
    parameters: {
      path: {
        type: 'string',
        required: true,
        description: 'Path to the existing .docx file, relative to the session workspace or absolute inside it.',
      },
      paragraphs: {
        type: 'array',
        items: { type: 'string' },
        description: 'Paragraphs to append in document order. Optional.',
      },
      bullets: {
        type: 'array',
        items: { type: 'string' },
        description: 'Bullet list items appended after the paragraphs. Optional.',
      },
      table: {
        type: 'object',
        additionalProperties: false,
        properties: {
          headers: {
            type: 'array',
            items: { type: 'string' },
            required: true,
            description: 'Table column headers (bold).',
          },
          rows: {
            type: 'array',
            items: { type: 'array', items: { type: 'string' } },
            required: true,
            description: 'Table body rows; each row should match the header column count.',
          },
        },
        description: 'One optional table appended after the text content.',
      },
    },
    output: {
      schema: WORD_UPDATE_OUTPUT,
      render: (_args, value: any) => [{
        type: 'text',
        text: `Appended to Word document ${value.path} (${value.sizeBytes} bytes; ${value.appendedParagraphs} paragraph(s), ${value.appendedBullets} bullet(s), ${value.appendedTableRows} table body row(s) appended).`,
      }],
    },
    presentCall: (args) => ({
      card: 'generic',
      title: `Update ${args.path}`,
      kind: 'edit',
      locations: [{ path: args.path }],
    }),
    async execute(args: WordUpdateArgs, exec: ToolRunContext) {
      const target = await resolveOfficePath(exec, ctx, args.path, ['.docx'], true)
      const { paragraphs: paragraphCount, cells } = wordCreateCounts(args)
      if ((args.paragraphs?.length ?? 0) === 0 && (args.bullets?.length ?? 0) === 0 && args.table === undefined) {
        throw new Error('word_update needs at least one of paragraphs, bullets, or table')
      }
      if (paragraphCount > 10_000) throw new Error('too many paragraphs/bullets/table rows (maximum 10000)')
      if (cells > 200_000) throw new Error('too many table cells (maximum 200000)')
      exec.signal.throwIfAborted()

      const { bytes } = await readOfficeBytes(exec, ctx, target.target)
      const zip = readZip(bytes)
      const documentXml = readZipXmlPart(zip, 'word/document.xml')
      if (documentXml === null) {
        throw new Error('the .docx has no word/document.xml part; is this a valid Word file?')
      }
      const fragment = buildAppendFragment(args)
      const updated = appendBeforeSectPr(documentXml, fragment)
      const parts: ZipPart[] = []
      for (const name of zip.entryNames()) {
        if (name === 'word/document.xml') {
          parts.push({ name, content: updated })
          continue
        }
        if (!zip.entryIsAsciiSafe(name)) {
          throw new Error(`zip entry "${name}" contains binary (non-ASCII) bytes; the update path re-publishes through the official UTF-8 text channel and cannot round-trip binary parts`)
        }
        parts.push({ name, content: zip.entryText(name) })
      }
      const text = buildAsciiZip(parts)
      exec.signal.throwIfAborted()
      const sizeBytes = await saveOfficeText(exec, ctx, target.target, text)
      return {
        path: target.display,
        sizeBytes,
        appendedParagraphs: args.paragraphs?.length ?? 0,
        appendedBullets: args.bullets?.length ?? 0,
        appendedTableRows: args.table?.rows.length ?? 0,
      }
    },
  }))
}
